/** @format */

export enum userActionsTypes {
	GET_USER_SUCCESS = "GET_USER_SUCCESS",
	GET_USER_ERROR = "GET_USER_ERROR",
	GET_USER_LOADING = "GET_USER_LOADING",
	GET_USER_TOURS_SUCCESS = "GET_USER_TOURS_SUCCESS",
	GET_USER_TOURS_ERROR = "GET_USER_TOURS_ERROR",
	GET_LOCATIONS = "GET_LOCATIONS",
	GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR",
	GET_GUIDE_TOURS_SUCCESS = "GET_GUIDE_TOURS_SUCCESS",
	GET_GUIDE_TOURS_ERROR = "GET_GUIDE_TOURS_ERROR",
	GET_TOUR_BY_ID = "GET_TOUR_BY_ID",
	GET_LOCATION_BY_ID = "GET_LOCATION_BY_ID",
	GET_USER_BOOKINGS_SUCCESS = "GET_USER_BOOKINGS_SUCCESS",
	GET_ONE_USER = "GET_ONE_USER",
	FETCH_COMMENTS = "FETCH_COMMENTS",
}
