/** @format */

export const authActionTypes = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	REGISTER_REQUEST: "REGISTER_REQUEST",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAILURE: "REGISTER_FAILURE",
	LOGOUT: "LOGOUT",
	EMAIL_VERIFIED: "EMAIL_VERIFIED",
	SET_AUTH_STATE: "SET_AUTH_STATE",
}
